---
language: php

php: "7.4"

before_install:
  - echo "memory_limit=16G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install

script:
  - ./vendor/bin/phpunit ./tests
  - ./vendor/bin/phpcs --standard=PSR12 ./src ./tests ./scripts
